### ISSUE TITLE
Hi i need a help.

### ISSUE THREAD

**Issue by hackevil** [Mrigank11/embetacloud#20]
i just deployed your app on heroku few minutes later but suddenly using it for few minutes, heroku just said that there is no such app. I think that your script is banned by heroku please fix it

**Comment by shashi007** [comment]
This can't be fixed, Heroku will detect the app and disable it. Better buy a vps and use it.

**Comment by Mrigank11** [comment]
I would recommend to try arukas.io , it's free till 2030 :)

**Comment by hackevil** [comment]
@Mrigank11 hi thanks for your reply can please tell me how can i deploy it to arukas.io

**Comment by cinetube** [comment]
@Mrigank11  how can i deploy it to arukas.io?

**Comment by Mrigank11** [comment]
@hackevil @cinetube Here are the steps : 

1. Register for an account on https://app.arukas.io/sign_up/
2. Wait for Confirmation. (have patience, it took 14 days in my case)
3. Create a new Application, the necessary things are : 
    - image: `mrigank11/embetacloud`
    - port: `3000`
    - fill out ENVs with GOOGLE_CLIENT_ID..etc. (listed in README)
    - CMD: `npm start`
4. Hit `Create Application`! That's All

Good Luck for Step 2

@hackevil I'm busy for some months due to examinations, I'll then create a new Project like FileStacks to upload to multiple clouds so that others can use that too. So sorry, but you've to wait for sometime.

**Comment by hackevil** [comment]
@Mrigank11 thanks buddy for the info and best of luck for your exams.

**Comment by ipainirfan** [comment]
hello sir! i do not understand with GOOGLE_REDIRECT_URL. Is it possible if i fill with http://localhost? and i try to deploy the image using openshift instead of arukas

**Comment by Mrigank11** [comment]
@ipainirfan `GOOGLE_REDIRECT_URL` is the URL to oauth callback receiver page, which is : `url to your site`/oauthCallback

For Example: on local system you'll set it to http://localhost:3000/oauthCallback

Now in your case(openshift), you'll get url to your site(like myapp.rhcloud.com) so you'll set: http://myapp.rhcloud.com/oauthCallback
