### ISSUE TITLE
Cannot Login To Mega

### ISSUE THREAD

**Issue by vivekcan** [Mrigank11/embetacloud#54]
Hey i cannot login to mega with my credentials please help me with it.
It only shows error msg when clicked on login after filling the mega credentials.

![screenshot_20181223-025722](https://user-images.githubusercontent.com/46073911/50378727-b0896e80-065e-11e9-8515-709945376672.png)

**Comment by Mrigank11** [comment]
By seeing that `/oauth/` path in your screenshot, I'm guessing that you did not select Mega.

You're trying to login using google without setting up proper credentials, that's why that error is there.

To use mega, first choose Mega from the "Cloud" icon. Then try logging in by clicking on the "Person" icon.

**Comment by vivekcan** [comment]
Thanks for ur reply it was just a silly mistake i didn't verified my account so it was not able to login.
